
package Mipaquete;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;



public class NewJFrame extends javax.swing.JFrame {

    int temperatura;
    String subir;
    String bajar;
    
    public NewJFrame() {
        initComponents();
        this.setTitle("Termometro");
         this.setLocationRelativeTo(NewJFrame.this);
         this.setResizable(false);
         Image ico = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/1212.jpg"));
         this.setIconImage(ico);
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Layout = new javax.swing.JPanel();
        txtTermometro = new javax.swing.JLabel();
        txtTemperatura = new javax.swing.JLabel();
        Barra = new javax.swing.JProgressBar();
        buttonSubir = new javax.swing.JButton();
        buttonBajar = new javax.swing.JButton();
        txtSubir = new javax.swing.JLabel();
        txtBajar = new javax.swing.JLabel();
        TemperaturaActual = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtTermometro.setText("Termometro");

        txtTemperatura.setText("Temperatura");

        Barra.setForeground(new java.awt.Color(0, 204, 0));
        Barra.setAutoscrolls(true);
        Barra.setBorder(javax.swing.BorderFactory.createTitledBorder("Progreso"));

        buttonSubir.setText("+");
        buttonSubir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSubirActionPerformed(evt);
            }
        });

        buttonBajar.setText("-");
        buttonBajar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBajarActionPerformed(evt);
            }
        });

        txtSubir.setText("Subir");

        txtBajar.setText("Bajar");

        TemperaturaActual.setEditable(false);
        TemperaturaActual.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TemperaturaActual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TemperaturaActualActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LayoutLayout = new javax.swing.GroupLayout(Layout);
        Layout.setLayout(LayoutLayout);
        LayoutLayout.setHorizontalGroup(
            LayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LayoutLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(LayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LayoutLayout.createSequentialGroup()
                        .addGroup(LayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtBajar)
                            .addComponent(txtSubir))
                        .addGap(43, 43, 43)
                        .addGroup(LayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonSubir, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buttonBajar, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(112, 112, 112))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LayoutLayout.createSequentialGroup()
                        .addComponent(Barra, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LayoutLayout.createSequentialGroup()
                        .addComponent(txtTermometro)
                        .addGap(118, 118, 118))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LayoutLayout.createSequentialGroup()
                        .addComponent(txtTemperatura)
                        .addGap(42, 42, 42)
                        .addComponent(TemperaturaActual, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))))
        );
        LayoutLayout.setVerticalGroup(
            LayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LayoutLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(txtTermometro)
                .addGap(44, 44, 44)
                .addGroup(LayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTemperatura)
                    .addComponent(TemperaturaActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(Barra, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(LayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSubir)
                    .addComponent(txtSubir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(LayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonBajar)
                    .addComponent(txtBajar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(Layout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(Layout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSubirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSubirActionPerformed
   temperatura=temperatura+1;
        subir= Integer.toString(temperatura);
        
        TemperaturaActual.setText(bajar);   // TODO add your handling code here:
        Barra.setValue(temperatura);        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSubirActionPerformed

    private void buttonBajarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBajarActionPerformed
   
         temperatura=temperatura-1;
        bajar= Integer.toString(temperatura);
        
        TemperaturaActual.setText(subir);
        Barra.setValue(temperatura);        // TODO add your handling code here:
    }//GEN-LAST:event_buttonBajarActionPerformed

    private void TemperaturaActualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TemperaturaActualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TemperaturaActualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar Barra;
    private javax.swing.JPanel Layout;
    private javax.swing.JTextField TemperaturaActual;
    private javax.swing.JButton buttonBajar;
    private javax.swing.JButton buttonSubir;
    private javax.swing.JLabel txtBajar;
    private javax.swing.JLabel txtSubir;
    private javax.swing.JLabel txtTemperatura;
    private javax.swing.JLabel txtTermometro;
    // End of variables declaration//GEN-END:variables
}
